# theme: jekyll-theme-architect
# SEOTitle: smartfish Blog

title: smartfish Blog
brief-intro: someone
description: "Nothing to say"
description_footer: "Nothing again"

baseurl: ""
url: "https://smartfish.github.io"
permalink: /:year/:month/:day/:title/

github_username: smartfish
twitter_username:
facebook_username:
email: yudongliang@hotmail.com
weibo_username:
zhihu_username:
linkedIn_username:
dribbble_username:

duoshuo_shortname:
disqus_shortname:

baidu_tongji_id:
google_analytics_id:

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

category_dir: category/
tag_dir: tag/

excerpt_separator: "\n\n\n\n"

paginate: 10
